name: evote_mobile
description: E-Vote E-Voting Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & Networking
  http: ^1.2.0
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Cryptography
  pointycastle: ^3.9.1
  cryptography: ^2.7.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.3.3
  
  # Biometric Auth
  local_auth: ^2.2.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/